SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OW_SUPPLIER] (
		[SUPPLIER_ID]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NAME]            [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ADDRESS]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
CREATE NONCLUSTERED INDEX [OW_SUPPLIER_IDX]
	ON [dbo].[OW_SUPPLIER] ([SUPPLIER_ID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[OW_SUPPLIER] SET (LOCK_ESCALATION = TABLE)
GO
