SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OW_RECENT_ORDERS] (
		[ORDER_ID]       [decimal](38, 0) NOT NULL,
		[CUST_ID]        [decimal](38, 0) NOT NULL,
		[ORDER_DATE]     [datetime2](7) NULL
)
GO
ALTER TABLE [dbo].[OW_RECENT_ORDERS] SET (LOCK_ESCALATION = TABLE)
GO
