SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OW_ORDERS] (
		[ORDER_ID]       [decimal](38, 0) NOT NULL,
		[CUST_ID]        [decimal](38, 0) NOT NULL,
		[ORDER_DATE]     [datetime2](7) NULL
)
GO
ALTER TABLE [dbo].[OW_ORDERS]
	ADD
	CONSTRAINT [ORDERS_PK]
	PRIMARY KEY
	CLUSTERED
	([ORDER_ID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[OW_ORDERS]
	WITH CHECK
	ADD CONSTRAINT [OW_ORDERS_CUSTOMERS_REF]
	FOREIGN KEY ([CUST_ID]) REFERENCES [dbo].[OW_CUSTOMERS] ([CUST_ID])
ALTER TABLE [dbo].[OW_ORDERS]
	CHECK CONSTRAINT [OW_ORDERS_CUSTOMERS_REF]

GO
ALTER TABLE [dbo].[OW_ORDERS] SET (LOCK_ESCALATION = TABLE)
GO
