SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TPC_C_BLOCK_INFO] (
		[TABLENAME]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CURRENT_BLOCK]     [int] NOT NULL,
		[MAX_BLOCK]         [int] NOT NULL
)
GO
ALTER TABLE [dbo].[TPC_C_BLOCK_INFO]
	ADD
	CONSTRAINT [PK__TPC_C_BL__36580732222BF7CA]
	PRIMARY KEY
	CLUSTERED
	([TABLENAME])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPC_C_BLOCK_INFO] SET (LOCK_ESCALATION = TABLE)
GO
