SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OW_ORDER_LINES] (
		[ORDER_ID]     [decimal](38, 0) NOT NULL,
		[I_LINE]       [decimal](38, 0) NOT NULL,
		[PART_ID]      [decimal](38, 0) NOT NULL,
		[QTY]          [decimal](38, 0) NOT NULL,
		[VALUE]        [decimal](38, 0) NULL,
		[FILLED]       [decimal](38, 0) NULL,
		[PAID]         [decimal](38, 0) NULL
)
GO
ALTER TABLE [dbo].[OW_ORDER_LINES]
	ADD
	CONSTRAINT [OW_LINE_PK]
	PRIMARY KEY
	CLUSTERED
	([ORDER_ID], [PART_ID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[OW_ORDER_LINES]
	ADD
	CONSTRAINT [DF__OW_ORDER___VALUE__182C9B23]
	DEFAULT ((0)) FOR [VALUE]
GO
ALTER TABLE [dbo].[OW_ORDER_LINES]
	ADD
	CONSTRAINT [DF__OW_ORDER___FILLE__1920BF5C]
	DEFAULT ((0)) FOR [FILLED]
GO
ALTER TABLE [dbo].[OW_ORDER_LINES]
	ADD
	CONSTRAINT [DF__OW_ORDER_L__PAID__1A14E395]
	DEFAULT ((0)) FOR [PAID]
GO
ALTER TABLE [dbo].[OW_ORDER_LINES]
	WITH CHECK
	ADD CONSTRAINT [OW_LINES_ORDER_REF]
	FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[OW_ORDERS] ([ORDER_ID])
ALTER TABLE [dbo].[OW_ORDER_LINES]
	CHECK CONSTRAINT [OW_LINES_ORDER_REF]

GO
ALTER TABLE [dbo].[OW_ORDER_LINES]
	WITH CHECK
	ADD CONSTRAINT [OW_LINES_PART_REF]
	FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[OW_PARTS] ([PART_ID])
ALTER TABLE [dbo].[OW_ORDER_LINES]
	CHECK CONSTRAINT [OW_LINES_PART_REF]

GO
ALTER TABLE [dbo].[OW_ORDER_LINES] SET (LOCK_ESCALATION = TABLE)
GO
