SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OW_PARTS] (
		[PART_ID]                [decimal](38, 0) NOT NULL,
		[SUPPLIER_ID]            [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PART_DESC]              [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PARENT_PART_ID]         [decimal](38, 0) NULL,
		[SUPPLIER_PART_ID]       [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PRICE]                  [decimal](38, 0) NULL,
		[BIN]                    [decimal](38, 0) NOT NULL,
		[QTY_ON_HAND]            [decimal](38, 0) NULL,
		[RESTOCK_QTY]            [decimal](38, 0) NULL,
		[BACKUP_SUPPLIER_ID]     [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [dbo].[OW_PARTS]
	ADD
	CONSTRAINT [OW_PARTS_PK]
	PRIMARY KEY
	CLUSTERED
	([PART_ID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[OW_PARTS]
	ADD
	CONSTRAINT [DF__OW_PARTS__PRICE__1CF15040]
	DEFAULT ((0)) FOR [PRICE]
GO
ALTER TABLE [dbo].[OW_PARTS]
	ADD
	CONSTRAINT [DF__OW_PARTS__QTY_ON__1DE57479]
	DEFAULT ((0)) FOR [QTY_ON_HAND]
GO
ALTER TABLE [dbo].[OW_PARTS]
	ADD
	CONSTRAINT [DF__OW_PARTS__RESTOC__1ED998B2]
	DEFAULT ((0)) FOR [RESTOCK_QTY]
GO
ALTER TABLE [dbo].[OW_PARTS] SET (LOCK_ESCALATION = TABLE)
GO
